### ISSUE TITLE
Use combustion for specs?

### ISSUE THREAD

**Issue by ddeyoung** [spud-rails/spud_core_admin#1]
I came across an issue in the Refinery repo where they moved to a gem called combustion (https://rubygems.org/gems/combustion) to remove the dependency of needing a full app to test engines. It could be work a look to see if it could work without being a bear to maintain the tests.

**Comment by davydotcom** [comment]
Lets hold on this and think about it more. It is a good potential.

**Comment by ddeyoung** [comment]
Agreed, I was mostly making a note of it for future reference.

**Comment by ddeyoung** [comment]
The dummy test app method has been added to the project and all current tests are now passing.
