### ISSUE TITLE
Working with sunspot:solr

### ISSUE THREAD

**Issue by drKreso** [spud-rails/spud_core_admin#6]
Hi, 

I think you made a great gem for image manipulation. 

I did have one problem with it. When used in combination with sunspot_solr it messes up the indexing. Core of the problem is monkeypatching over searchable method.

It took me a couple of hours to find this:

module Spud::Searchable
    extend ActiveSupport::Concern
    included do
        extend ClassMethods
    end
    module ClassMethods
        def searchable
            # puts "Place Holder For #{self.name}"
        end
    end
end

After a rename sunspot_solr started working properly

module Spud::Searchable
    extend ActiveSupport::Concern
    included do
        extend ClassMethods
    end
    module ClassMethods
        def spud_searchable
            # puts "Place Holder For #{self.name}"
        end
    end
end

Do you think this could be changed not to interfere with sunspot?

Best Regards,

Kreso

**Comment by davydotcom** [comment]
Not sure which gem you are referring to photos or media? Either way. This is indeed a core bug and was unaware this affected solr. Unfortunately both spud_cms and spud_blog depend on this directive. I will try and push updates out within the next day.

**Comment by drKreso** [comment]
Photos. Great.

**Comment by davydotcom** [comment]
Version 0.9.10 for dependency spud_core released. Also associated releases for spud_cms, spud_blog, and spud_search have been released to accomodate this change. searchable now spud_searchable.

**Comment by drKreso** [comment]
Hi. This looks good. I have different problem that I am not sure the cause.

It might be I've messed it up yesterday. But I've removed all gems and
reinstalled.

couldn't find file 'codemirror/themes/night'
  (in /Users/kbojcic/.rvm/gems/ruby-2.0.0-preview1/gems/spud_core-0.9.11/app/assets/stylesheets/spud/admin/application.css:5)

**Comment by davydotcom** [comment]
Whoops! sorry about that, to get this change out I had to push some other changes out early. Missing a require line in the engine.rb we are pushing a release out at this very moment.

**Comment by davydotcom** [comment]
Released spud_core version 0.9.12!

**Comment by drKreso** [comment]
Now jQuery died :)
upload is not working (single or mulitple) - I am not sure if it's me...
this what happens on "Save"

Uncaught Error: Syntax error, unrecognized expression: <div
class="spud_admin_photo_progress" <h6> <span
class="spud_admin_photo_progress_filename"></span>: <span
class="spud_admin_photo_progress_status">Uploading</span> </h6> <div
class="progress progress-striped active"> <div class="bar" style="width:
0;"></div> </div> </div>
jquery.js:4412http://localhost:3000/assets/jquery.js?body=1
 http://localhost:3000/assets/jquery.js?body=1
 http://localhost:3000/assets/jquery.js?body=1

**Comment by davydotcom** [comment]
Ok so may need some more debug information from you, however. It is important to note jQuery updated to 1.9 on Sunday for jquery-rails gem. We are actively working to make sure spud is compliant with the new version. In the meantime, you can try to use an older version of jquery-rails in your gemfile using:
gem 'jquery-rails', '2.1.4'

Please let us know if that works.

**Comment by drKreso** [comment]
You are right. Thaks so much.

**Comment by davydotcom** [comment]
spud_photos update available with new jquery support and a few other fixes.
